models:
  - type: main
    engine: amazon_bedrock
    model: anthropic.claude-v2

core:
  embedding_search_provider:
    name: amazon_bedrock_embedding
    parameters:
      embedding_engine: amazon_bedrock
      embedding_model: amazon.titan-embed-text-v1

knowledge_base:
  embedding_search_provider:
    name: amazon_bedrock_embedding
    parameters:
      embedding_engine: amazon_bedrock
      embedding_model: amazon.titan-embed-text-v1